const SERVER_BASE_URL = 'http://localhost:3000/';

const CONTROLLER_SERVICE_OPENAI_ID = 'service-openai';
const CONTROLLER_SERVICE_OPENAI_GET_PRODUCT_STRUCTURE = 'get-product-structure';
const CONTROLLER_SERVICE_OPENAI_GET_FUNCTIONS = 'get-functions';

const CONTROLLER_OPENAI_COMPLETIONS_ID = 'openai-completions';

const CONTROLLER_PROCESS_ID = 'process';

const CONTROLLER_PRODUCT_ID = 'product';

module.exports = {
  SERVER_BASE_URL,
  CONTROLLER_SERVICE_OPENAI_ID,
  CONTROLLER_SERVICE_OPENAI_GET_PRODUCT_STRUCTURE,
  CONTROLLER_SERVICE_OPENAI_GET_FUNCTIONS,
  CONTROLLER_OPENAI_COMPLETIONS_ID,
  CONTROLLER_PROCESS_ID,
  CONTROLLER_PRODUCT_ID,
};
